const profileData = () => [
  {
    userName: "rea-doe-xs-1",
    fullName: "Rea Doe",
    school: "OS Example School",
    grade: "7. Razred",
    dateOfBirth: "06.06.2001",
    ovearallRank: "24th",
    gradeRank: "2nd",
    schoolRank: "1st",
  },
  {
    userName: "martin222",
    fullName: "Martin Martinovic",
    school: "OS Example School",
    grade: "1. Razred",
    dateOfBirth: "04.01.2004",
    ovearallRank: "2th",
    gradeRank: "17nd",
    schoolRank: "2nd",
  },
  {
    userName: "miroslav12345",
    fullName: "Miroslav Mikavica",
    school: "OS Example School",
    grade: "9. Razred",
    dateOfBirth: "04.01.2000",
    ovearallRank: "10th",
    gradeRank: "5nd",
    schoolRank: "3nd",
  },
  {
    userName: "igorigorevic",
    fullName: "Igor Petrovic",
    school: "OS Example School",
    grade: "6. Razred",
    dateOfBirth: "01.01.2005",
    ovearallRank: "10th",
    gradeRank: "5nd",
    schoolRank: "4nd",
  },
];
